{{ range .Values.alerts }}
apiVersion: core.humio.com/v1alpha1
kind: HumioAlert
metadata:
  name: {{ include "chart.fullname" $ }}-{{ .name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 3 }}
  {{- end }}
spec:
  managedClusterName: {{ $.Values.managedClusterName }}
  viewName: {{ $.Values.viewPrefix | default "" }}{{ .viewName }}
  name: {{ .name }}
  query:
    queryString: {{ .query.queryString }}
    start: {{ .query.start | default "5m" }}
    end: {{ .query.end | default "now" }}
    isLive: {{ .query.isLive | default "false"}}
  throttleTimeMillis: {{ .throttleTimeMillis | default "60000"}}
  silenced: {{ .silenced | default "false"}}
  actions: {{ $.Values.actions }}
{{ end }}
